### ISSUE TITLE
Rebase to v1.10.18 of root geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-ipfs-state-validator#23]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] v3 release that uses the new v1.10.18 release of geth (off of https://github.com/vulcanize/eth-ipfs-state-validator/tree/release-v3.0.0)
- [x] v4 release that uses the new v1.10.18 release of geth (off of https://github.com/vulcanize/eth-ipfs-state-validator/tree/release-v4.0.0-alpha)

This will also require updating the dependency on ipfs-ethdb to use the corresponding branches resultant from: https://github.com/vulcanize/ipfs-ethdb/issues/34

**Comment by abdulrabbani00** [comment]
Needs Merging: https://github.com/vulcanize/eth-ipfs-state-validator/pull/25
