### ISSUE TITLE
Improve test fixtures

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-ipfs-state-validator#37]
- [ ] Valid state and storage
- [ ] Missing state intermediate node(s)
- [ ] Missing state leaf node(s)
- [ ] Missing storage intermediate node(s)
- [ ] Missing storage leaf node(s)

**Comment by i-norden** [comment]
This will probably involve running ipld-eth-state-snapshot at various heights and configured to fail at certain points and saving the CSV file ouput so that it can be dumped into a Postgres database and tested against

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/eth-ipfs-state-validator/issues/5
