### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-ipfs-state-validator#59]
```
# github.com/cerc-io/eth-ipfs-state-validator/v4/pkg_test [github.com/cerc-io/eth-ipfs-state-validator/v4/pkg.test]
./validator_test.go:231:10: undefined: ResetTestDB
./validator_test.go:282:10: undefined: ResetTestDB
./validator_test.go:306:10: undefined: ResetTestDB
./validator_test.go:333:13: undefined: PublishRaw
./validator_test.go:337:13: undefined: PublishRaw
FAIL	github.com/cerc-io/eth-ipfs-state-validator/v4/pkg [build failed]
```

These methods appear to have been removed in https://github.com/cerc-io/eth-ipfs-state-validator/pull/45/files, it looks like they were supposed to be replaced by a new package but that never got committed and since this repo has no CICD it was not caught until Mike dug in deeper. Thank you for finding this @ABastionOfSanity. I have a patch ready, don't want you to be blocked by this.

**Comment by ABastionOfSanity** [comment]
PRs merged, workflow created and extended to run the tests as well as the basic build.
